// Code generated by goctl. DO NOT EDIT.
// Source: userscore.proto

package server

import (
	"context"

	"go-zero/mall/userscore/internal/logic"
	"go-zero/mall/userscore/internal/svc"
	"go-zero/mall/userscore/types/userscore"
)

type UserscoreServer struct {
	svcCtx *svc.ServiceContext
	userscore.UnimplementedUserscoreServer
}

func NewUserscoreServer(svcCtx *svc.ServiceContext) *UserscoreServer {
	return &UserscoreServer{
		svcCtx: svcCtx,
	}
}

func (s *UserscoreServer) Ping(ctx context.Context, in *userscore.Request) (*userscore.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserscoreServer) SaveUserScore(ctx context.Context, in *userscore.UserScoreRequest) (*userscore.UserScoreResponse, error) {
	l := logic.NewSaveUserScoreLogic(ctx, s.svcCtx)
	return l.SaveUserScore(in)
}
